Modules/Crypt/Http/routes.php
<?php

Route::group(['middleware' => ['web', 'auth'], 'namespace' => 'Modules\Crypt\Http\Controllers'], function()
{
    Route::resource('portfolio', 'PortfolioController');
    Route::resource('capital', 'CapitalController');
    Route::resource('news', 'NewsController');

    Route::resource('ticker', 'TickerController');
});

Modules/Crypt/Entities/Portfolio.php
<?php

namespace Modules\Crypt\Entities;

use App\Models\Base;
use App\Models\User\User;

class Portfolio extends Base
{
    const FIAT_RUB = 'RUB';
    const FIAT_USD = 'USD';

    protected $fillable = [
        'coin', 'coin_val', 'fiat', 'cost_val', 'user_id', 'stock_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function course()
    {
        return $this->hasOne(Course::class, 'symbol', 'coin');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function stock()
    {
        return $this->hasOne(Stock::class, 'id', 'stock_id');
    }

    /**
     * @return float
     */
    public function getDeposit()
    {
        $data = Portfolio::where('user_id', Auth::user()->id)
            ->selectRaw('(coin_val * cost_val) as result')
            ->get()
            ->sum('result');

        return round($data, 2);
    }
    
    /**
     * @param null $fiat
     * @return array|mixed|string
     */
    public function getFiats($fiat = null)
    {
        $data = [
            self::FIAT_USD => self::FIAT_USD,
            self::FIAT_RUB => self::FIAT_RUB,
        ];

        return $fiat !== null ? ($data[$fiat] ?? '') : $data;
    }

    /**
     * @param null $coin
     * @return string
     */
    public function getCoins($coin = null)
    {
        $url = 'https://api.coinmarketcap.com/v1/ticker/';
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = json_decode(curl_exec($ch));

        foreach ($result as $r) {
            $data[$r->symbol] = $r->name;
        }

        return $coin !== null ? ($data[$coin] ?? '') : $data;
    }

    /**
     * @return string
     */
    public function getRateOldAttribute()
    {
        return $this->cost_val . ' ' . $this->fiat;
    }

    /**
     * @return string
     */
    public function getRateNowAttribute()
    {
        return $this->course->price_usd . ' ' . $this->fiat;
    }

    /**
     * @return string
     */
    public function getCostOldAttribute()
    {
        return round($this->cost_val * $this->coin_val, 2) . ' ' . $this->fiat;
    }

    /**
     * @return string
     */
    public function getCostNowAttribute()
    {
        return round($this->course->price_usd * $this->coin_val, 2) . ' ' . $this->fiat;
    }

    /**
     * @return string
     */
    public function getGainLostAttribute()
    {
        return round($this->coin_val * ($this->course->price_usd - $this->cost_val), 2);
    }
}

Modules/Crypt/Http/Controllers/PortfolioController.php
<?php

namespace Modules\Crypt\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Crypt\Entities\Portfolio;
use Auth;
use Modules\Crypt\Entities\Stock;
use Event;

class PortfolioController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        Event::fire('courses.update');

        return view('crypt::portfolio.index', [
            'portfolio' => Portfolio::where('user_id', Auth::user()->id)
                ->with('user', 'course', 'stock')
                ->paginate(20),
            'deposit' => Auth::user()->getDeposit(),
            'balance' => Auth::user()->getGainLost()
        ]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return $this->getForm();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        Portfolio::upsert($request->input());

        return redirect(route('portfolio.index'));
    }

    /**
     * @param Portfolio $portfolio
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Portfolio $portfolio)
    {
        return $this->getForm($portfolio->id);
    }

    /**
     * @param Portfolio $portfolio
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Portfolio $portfolio)
    {
        Portfolio::destroy($portfolio->id);

        return redirect(route('portfolio.index'));
    }

    /**
     * @param null $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    private function getForm($id = null)
    {
        $portfolio = $id ? Portfolio::find($id) : new Portfolio();

        return view('crypt::portfolio.form', [
            'portfolio' => $portfolio,
            'stocks' => $this->getStocks()
        ]);
    }

    /**
     * @return array
     */
    public function getStocks()
    {
        return Stock::pluck('stock', 'id')->toArray();
    }
}

Modules/Crypt/Resources/views/portfolio/form.blade.php
@extends('admin.layouts.form')

@section('content_form')
    {{ Form::model($portfolio, ['route' => 'portfolio.store', 'files' => true, 'class' => 'form-horizontal']) }}

        @component('admin.components.form.devider'){{ __('index.main_data') }}@endcomponent

        <div class="form-group">
            {{ Form::adminText('coin_val', 'Количество', 3, 3) }}
            {{ Form::adminSelect('coin', 'Монета', $portfolio->getCoins(), 2, 3) }}
        </div>

        <div class="form-group">
            {{ Form::adminText('cost_val', 'Курс покупки', 3, 3) }}
            {{ Form::adminSelect('fiat', 'Фиат', $portfolio->getFiats(), 2, 3) }}
        </div>

        <div class="form-group">
            {{ Form::adminSelect('stock_id', 'Биржа', $stocks, 3, 8) }}
        </div>

        @if ($portfolio->exists)
            {{ Form::hidden('id', $portfolio->id) }}
        @endif

        {{ Form::hidden('user_id', Auth::id()) }}

        @component('admin.components.form.devider'){{ __('index.actions') }}@endcomponent

    {{ Form::adminSubmit() }}

    {{Form::close()}}
@endsection

Modules/Crypt/Resources/views/portfolio/index.blade.php
@extends('admin.layouts.table')

@section('content_table')

    @section('title', 'Portfolio')
    @section('routeButton', route('portfolio.create'))
    @section('titleButton', 'Add Coin')

    @if ($portfolio->count())
    <table class="table table-bordered table-responsive table-striped">
        <thead>
        <tr class="bg-light">
            <th>Монета</th>
            <th>Количество</th>
            <th>Курс (покупки/текущий)</th>
            <th>Сумма (затрат/текущая)</th>
            <th>Прибыль/Убыток</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>

        @forelse($portfolio as $p)
            <tr>
                <td>
                    <span class="label label-default">{{ $p->coin }}</span>
                </td>
                <td>
                    {{ rtrim($p->coin_val, '0') }}
                    <a href="{{ $p->stock->stock_url }}" target="_blank"
                       class="label label-primary pull-right"
                       style="padding: .1em .4em; font-size: 75%; line-height: 15px;">
                        {{ $p->stock->stock }}
                    </a>
                </td>
                <td>{{ $p->rate_old }} / {{ $p->rate_now }}</td>
                <td>{{ $p->cost_old }} / {{ $p->cost_now }}</td>
                <td class="text-{{ ($p->gain_lost > 0) ? 'primary' : 'danger'}}">{{ $p->gain_lost }} {{ $p->fiat }}</td>
                <td>
                    {{ Form::adminActions(
                        route('portfolio.edit', ['aff_system' => $p->id]),
                        route('portfolio.destroy', ['portfolio' => $p])
                    ) }}
                </td>
            </tr>
        @empty
            <tr><td colspan="6">{{ __('index.data_not_found') }}</td></tr>
        @endforelse
            <tr>
                <td colspan="2" class="text-right">Депозит: {{ $deposit }} {{ $p->fiat }}</td>
                <td colspan="1" class="text-right text-{{ ($balance > 0) ? 'primary' : 'danger'}}">Баланс: {{ $balance }} {{ $p->fiat }}</td>
                <td colspan="3" class="text-right">Итого: {{ $deposit + $balance }} {{ $p->fiat }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        {{ $portfolio->links() }}
    </div>
    @else
        <span>Пришло время добавить валюту!</span>
    @endif

@endsection